[theme]
base = "dark"
primaryColor = "#8aafd4"
backgroundColor = "#131110"
secondaryBackgroundColor = "#1c1916"
textColor = "#ede7de"
font = "sans serif"

[server]
headless = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false
